"""make Faculty.name unique

Revision ID: 065a1e06ff49
Revises: aa83db563bd4
Create Date: 2023-09-03 10:11:44.813428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065a1e06ff49'
down_revision: Union[str, None] = 'aa83db563bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'faculties', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculties', type_='unique')
    # ### end Alembic commands ###
