"""discard unique

Revision ID: 827d42c66cdb
Revises: 97dc169312b9
Create Date: 2023-09-03 11:29:19.138549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827d42c66cdb'
down_revision: Union[str, None] = '97dc169312b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('departments_name_key', 'departments', type_='unique')
    op.drop_constraint('faculties_name_key', 'faculties', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('faculties_name_key', 'faculties', ['name'])
    op.create_unique_constraint('departments_name_key', 'departments', ['name'])
    # ### end Alembic commands ###
