"""make  and  optional for 

Revision ID: 8376f3249969
Revises: 8a3327011c4a
Create Date: 2023-09-02 16:41:56.761595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8376f3249969'
down_revision: Union[str, None] = '8a3327011c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'governor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('classes', 'deputy_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'deputy_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('classes', 'governor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
