"""init

Revision ID: 8a3327011c4a
Revises: 
Create Date: 2023-09-02 15:44:49.612880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3327011c4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('level', sa.Enum('L100', 'L200', 'L300', 'L400', 'L500', 'L600', 'L700', name='level'), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('governor_id', sa.Uuid(), nullable=False),
    sa.Column('deputy_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('admission_mode', sa.Enum('UTME', 'DIRECT_ENTRY', name='admissionmode'), nullable=False),
    sa.Column('matriculation_number', sa.String(), nullable=True),
    sa.Column('jamb_registration_number', sa.String(), nullable=True),
    sa.Column('personal_email_address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('classes')
    op.drop_table('departments')
    op.drop_table('faculties')
    op.drop_table('schools')
    # ### end Alembic commands ###
