"""make School.name unique

Revision ID: aa83db563bd4
Revises: 8376f3249969
Create Date: 2023-09-02 17:48:15.346062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa83db563bd4'
down_revision: Union[str, None] = '8376f3249969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'schools', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', type_='unique')
    # ### end Alembic commands ###
